# Be sure to restart your server when you modify this file.
# your real file should be at your_app/config folder

# zinrelo account info

default: &default
   api_url    : api_url
   partner_id : partnerid
   api_key    : api_key

